### ISSUE TITLE
Not work with less

### ISSUE THREAD

**Issue by wangjiaojiao77** [elchininet/postcss-rtlcss#108]
My configuration is as follows:

`
{
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          { loader: 'less-loader' },
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [
                  postcssRTLCSS()
                ]
              }
            }
          }
        ]
      },
`

Then it reported an error:

ERROR in ./src/pages/haha/container/plan-md.less (./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./node_modules/postcss-loader/src??ref--7-3!./src/pages/okex/container/plan-md.less)
    Module build failed (from ./node_modules/postcss-loader/src/index.js):
    SyntaxError

    (10:5) Unknown word

       8 |   }
       9 |   .section-content {
    > 10 |     .gg();
         |     ^
      11 |     margin-top: 24px;
      12 |     .content {

postcss-rtlcss does not support less? Who can help me

**Comment by elchininet** [comment]
Hi @wangjiaojiao77, it would be good a link to the repo or the branch in which you are having the issue but looking at your configuration, something that you can try is to change the order of the loaders. Loaders are read in reverse order, so you are trying to run `postcss-loader` together with `postcss-rtlcss` before `less-loader`. First, compile your less code with `less-loader` and after that execute `postcss-loader` with any plugin.

```javascript
{
    test: /\.less$/,
    use: [
        { loader: 'style-loader' },
        { loader: 'css-loader' },
        {
            loader: 'postcss-loader',
            options: {
                postcssOptions: { plugins: [ postcssRTLCSS() ] }
            }
        },
        { loader: 'less-loader' }
    ]
}
```

**Comment by elchininet** [comment]
Hi @wangjiaojiao77, [here you have a repo](https://github.com/elchininet/postcss-rtlcss-less-and-sass) with a Webpack configuration to compile `Less` and `Sass` code. Please, check the configuration and check how the final CSS bundle is compiled without any issue. Closing this issue. Please, if you have another issue, open a new one.

Regards!

**Comment by wangjiaojiao77** [comment]
thanks, The problem was solved!
