### ISSUE TITLE
Is there any requirement on the postCSS-Loader version?

### ISSUE THREAD

**Issue by wangjiaojiao77** [elchininet/postcss-rtlcss#109]
The following code works:
`
"postcss": "^7.0.39",
"postcss-loader": "^4.3.0",
"postcss-rtlcss": "^1.7.2",
`

But The following code does not works:
`
"postcss": "^7.0.39",
"postcss-loader": "^3.0.0",
"postcss-rtlcss": "^1.7.2",
`

**Comment by elchininet** [comment]
Hi @wangjiaojiao77,

There are requirements for the `postcss` version, depending on it, you need to use the legacy version or not. Read [the Install section in the README](https://github.com/elchininet/postcss-rtlcss#install):

![image](https://user-images.githubusercontent.com/3728220/145777434-eb958a6c-e6b6-4889-8b6b-58c0c7b2c2ae.png)

And depending on the version, the import of the library is also different. Refer to [Basic usage in the README](https://github.com/elchininet/postcss-rtlcss#basic-usage):

![image](https://user-images.githubusercontent.com/3728220/145777884-f5067eea-40bd-4fa2-b145-2347c4d73da4.png)

Closing this issue.

> Duplicate of #69
