### ISSUE TITLE
None of the Directives works with next js

### ISSUE THREAD

**Issue by SarkarKurdish** [elchininet/postcss-rtlcss#114]
hey I have latest nextjs project this is my postcss file

`module.exports = {
  plugins: {
    tailwindcss: {},
    "postcss-flexbugs-fixes": {},
    "postcss-preset-env": {
      autoprefixer: {
        flexbox: "no-2009",
      },
      stage: 3,
      features: {
        "custom-properties": false,
      },
    },
    "postcss-rtlcss": {},
  },
};
`

postcss-rtlcss works fine the only thing that's not working is the Directives for example i put this in my main css file

/* rtl:begin:ignore */
body {
    background-color: blue;
}

/* rtl:end:ignore */

but it seems the Directives  don't work the background is blue in both rtl and ltr

**Comment by elchininet** [comment]
Hi @SarkarKurdish,

I think that you have misunderstood what that directive does. Take a look again at [its section](https://github.com/elchininet/postcss-rtlcss#rtlignore) in the documentation and the examples provided. This plugin is not intended to remove any rule from your CSS.

That directive just ignores a rule or a directive that should be flipped and it avoids creating the respective CSS for `ltr` and `rtl` (the rule or declaration will be the same in both directions).

If you want to declare background blue in `ltr` and background `transparent` in `rtl`, you can use the `/*rtl:{value}*/` directive, e.g:

```css
body {
  background: #blue /*rtl:transparent*/;
}
```

I pushed a small change to the [nextjs-postcss-rtlcss-example](https://github.com/elchininet/nextjs-postcss-rtlcss-example) project. Just execute this project and change the selector. you will see that the background of the `testContainer` element changes respectively.

Regards.

**Comment by SarkarKurdish** [comment]
Thanks for the response

I did what you have mentioned yet it didn't work

![image](https://user-images.githubusercontent.com/37934074/148681535-aa437f7e-6f03-4ec0-b8d9-501084f38d28.png)

the background stays blue in both rtl and ltr please note the package works fine in every aspect expect for the Directives

**Comment by SarkarKurdish** [comment]
> Thanks for the response
> 
> I did what you have mentioned yet it didn't work
> 
> ![image](https://user-images.githubusercontent.com/37934074/148681535-aa437f7e-6f03-4ec0-b8d9-501084f38d28.png)
> 
> the background stays blue in both rtl and ltr please note the package works fine in every aspect expect for the Directives

PS: I did copy the postcss file from your example still didn't work, i use SCSS btw can this be the problem?

**Comment by elchininet** [comment]
@SarkarKurdish,

It is relevant for the discussion that you are using `SASS`. If you test the example project which uses regular CSS, you will notice that it does work.

[SASS treats comments in a different way than regular CSS](https://sass-lang.com/documentation/syntax/comments). For comments placed outside the rules, you either need to remove [the compressed mode](https://sass-lang.com/documentation/cli/dart-sass#style) or start the comment with `/*!`. But if the comment is placed inside a declaration, **SASS** will remove it completely from the output. To bypass this, you should use [a SASS interpolation](https://sass-lang.com/documentation/interpolation) starting the comment with `/*!`:

```scss
body {
    background: blue #{"/*!rtl:transparent;*/"};
}
```

Regards.

**Comment by elchininet** [comment]
Hi @SarkarKurdish,

I have pushed a commit into the [nextjs-postcss-rtlcss-example](https://github.com/elchininet/nextjs-postcss-rtlcss-example) project showing how to put the comments in SASS. Check it out and let me know the results.

Regards.

**Comment by SarkarKurdish** [comment]
Thanks the issue resolved.

**Comment by elchininet** [comment]
Glad to know, @SarkarKurdish.
Regards!
