### ISSUE TITLE
How to support generating two CSS files?

### ISSUE THREAD

**Issue by wangjiaojiao77** [elchininet/postcss-rtlcss#116]
One is the original CSS file, and one is the RTL CSS file

**Comment by elchininet** [comment]
Hi @wangjiaojiao77,

Please, refer to [this issue](https://github.com/elchininet/postcss-rtlcss/issues/78).

Regards.

**Comment by wangjiaojiao77** [comment]
thanks a lot!

**Comment by wangjiaojiao77** [comment]
resolved
