### ISSUE TITLE
Do you support frameworks such as Vue and react

### ISSUE THREAD

**Issue by cy920820** [elchininet/postcss-rtlcss#159]

**Comment by elchininet** [comment]
Hi @cy920820,

This plugin is a [postcss](https://postcss.org/) plugin. You can hook this plugin into any framework that supports `postcss`. `Vue` and `React` are just `JavaScript` frameworks, you need to look at the framework that you use to process or generate the final `CSS`. Here you can find an [example repo](https://github.com/elchininet/nextjs-postcss-rtlcss-example) in which this plugin is being used in a Next.js project.

Closing this issue.

Regards
