### ISSUE TITLE
Ignore comments doesn't work

### ISSUE THREAD

**Issue by Ahmedelforjani** [elchininet/postcss-rtlcss#164]
I use vite with sass, and I want to ignore some @import files by rtl:being:ignore and rtl:end:ignore comments but that doesn't effect

**Comment by elchininet** [comment]
Hi @Ahmedelforjani,
Please, consult [this issue](https://github.com/elchininet/postcss-rtlcss/issues/114) and the responses given there, if that doesn‘t work for you, please, create a minimum reproducible repo to check what is failing.
Regards.

**Comment by elchininet** [comment]
Hi @Ahmedelforjani,
Have you followed the instructions given in the thread? Did they work for you?
If not, please, create a repo with a reproducible example to take a look at it.
Regards

**Comment by elchininet** [comment]
Hi @Ahmedelforjani,

It seems that you already solve your issue.

Please, open a new issue if you have followed the steps and you are still having troubles.

Regards
