### ISSUE TITLE
Media query + text-align: center not given precedence

### ISSUE THREAD

**Issue by kutnickclose** [elchininet/postcss-rtlcss#165]
Hi @elchininet,

At below 600px, I want the text to be centered aligned but will in fact be left aligned due to specificity.
![image](https://user-images.githubusercontent.com/6117662/181098383-921584a0-d634-4799-847a-154dbd6d731d.png)

Codesandbox with more similar code that I'm encountering with my configuration
https://codesandbox.io/s/cranky-violet-bx0v2w?file=/index.html

Even with the config `safeBothPrefix: true`, I'm not getting the .test1 in a media query to have a .dir in front of it.  

My full config is 
```
    ltrPrefix: '.dir-ltr',
    rtlPrefix: '.dir-rtl',
    bothPrefix: '.dir',
    safeBothPrefix: true,
    prefixSelectorTransformer: (prefix, selector) => `${prefix}${selector}`,
```

**Comment by kutnickclose** [comment]
Actually sorry, I made a mistake it seems to be okay.

**Comment by elchininet** [comment]
Hi @kutnickclose,
I think that you don‘t have the `safeBothPrefix` option set in `true` as you mentioned.
Anyway, it is good that you have solved the issue.
