### ISSUE TITLE
Backport nested at-rules to legacy version

### ISSUE THREAD

**Issue by kutnickclose** [elchininet/postcss-rtlcss#166]
Hi @elchininet,

Could this commit (https://github.com/elchininet/postcss-rtlcss/pull/90) get backported to the legacy version? I'm running into an issue where nested media queries are not getting the safe prefix.

**Comment by elchininet** [comment]
Hi @kutnickclose,
Let me check if I can add it to the legacy version.
I‘ll let you know.
Regards.

**Comment by elchininet** [comment]
Hi @kutnickclose,
That commit has been included in the [legacy version 1.8.2](https://www.npmjs.com/package/postcss-rtlcss/v/1.8.2).
Regards

**Comment by kutnickclose** [comment]
Appreciate it! thank you!
