### ISSUE TITLE
Including postcss-rtlcss with Angular12 with SCSS base styles later compiled to CSS

### ISSUE THREAD

**Issue by Kavshree** [elchininet/postcss-rtlcss#167]
I am trying to use this library in my Angular 12 project with a custom webpack. I am getting this error: "_Module build failed (from ./node_modules/sass-loader/dist/cjs.js): SassError: Invalid CSS after "i": expected 1 selector or at-rule, was 'import api from "!.' on line 1 of src/app/... from sass-loader/dist/cjs.js file_"

```
module.exports = (config, options) => {
    addRtlConfig = (config) => {
        return {
            ...config, *//has all the existing default configs*
            module: {
                ...config.module,
                rules: [
                    ...config.module.rules,
                    {
                    test: /\.scss$|\.sass$/,
                      use: [
                        'style-loader',
                        'css-loader',
                        {
                          'loader': 'postcss-loader',
                          'options': {
                            postcssOptions: {
                                plugins: () => [require('postcss-rtlcss')({})],
                            }
                          }
                        },
                        'sass-loader'
                      ]
                    },
                  ]
                }
            }
        }
    return addRtlConfig(config);
}
```

Please guide if I am using this incorrectly!

**Comment by elchininet** [comment]
Hi @Kavshree,
It is hard to support you without having your complete set up. Please, provide me with the link of the repo in which you are having your issue or create a minimum reproducible git repo in which the issue can be reproduced.
But before that, consult this [this issue](https://github.com/elchininet/postcss-rtlcss/issues/120). There, @MatasRut posted a git repo of an angular project using `SASS` and `postcss-rtlcss`, maybe it can help you.
Regards

**Comment by elchininet** [comment]
Hi @Kavshree, did you resolve your issue?
If the issue is not resolved, please, provide me with a repo in which the issue can be reproduced.
Regards
