### ISSUE TITLE
Using postcss-rtlcss in Vite & laravel-vite-plugin

### ISSUE THREAD

**Issue by ayaseensd** [elchininet/postcss-rtlcss#168]
Hello,

this is not an issue, it's a question,
how can I use postcss-rtlcss with Vite and laravel vite plugin?
any help or links appreciated

**Comment by elchininet** [comment]
Hi @ayaseensd,
In [this issue](https://github.com/elchininet/postcss-rtlcss/issues/160), @ak-14 created [a minimum reproducible repository](https://github.com/ak-14/postcss-rtlcss-issue-160) using `Vite`. Try to check if it works for you and let me know.
Regards.

**Comment by elchininet** [comment]
Hi @ayaseensd,
Were you able to implement the plugin in your project?
Regards

**Comment by elchininet** [comment]
Hi @ayaseensd,
It seems that you solved your question.
Closing this issue!

**Comment by elchininet** [comment]
Hi @ayaseensd,
I am glad that you solved it.
Regards!

**Comment by AmirJavaidSwe** [comment]
> Hello @elchininet , sorry for late reply, I was offline for long time I solve it by
> 
> `postcss.config.js file`
> 
> ```
> module.exports = {
>     plugins: [
>         require('postcss-rtlcss'),
>     ],
> };
> ```
> 
> and vite config file `vite.config.js file`
> 
> ```
> import { defineConfig } from 'vite';
> import laravel from 'laravel-vite-plugin';
> 
> export default defineConfig({
>     plugins: [
>         laravel([
>             'resources/sass/app.scss',
>             'resources/sass/custom.scss',
>             'resources/js/app.js',
>         ]),
>     ],
>     resolve: {
>         alias: [
>             {
>                 // this is required for the SCSS modules
>                 find: /^~(.*)$/,
>                 replacement: '$1',
>             },
>         ],
>     },
> });
> ```
> 
> I think it similar to your refered solution. Thank you again.

can you share your full solution here?
