### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ravshansbox** [elchininet/postcss-rtlcss#192]
Please, create github release for every version so that one can subscribe and be notified about new features.

**Comment by elchininet** [comment]
Hi @ravshansbox,
Sure, I‘ll implement it.
I‘ll let you know when it is done.
Regards.

**Comment by elchininet** [comment]
Hi @ravshansbox,
It is already implemented, from next deployment, also a Github release should be created in the repo.
Regards
