### ISSUE TITLE
Cannot read properties of undefined (reading 'some') with sass like mixin on first line

### ISSUE THREAD

**Issue by Vilz** [elchininet/postcss-rtlcss#204]
Hello!
In my nuxt-2 project, I'm trying to replace node-sass with a set of postcss plugins.
This is my config part

```
         postcss: {
             plugins: {
                 'postcss-nested': {},
                 'postcss-simple-vars': {
                     variables: variablesPostCss
                 },
                 'postcss-mixins': {
                     mixins: mixinsPostCss,
                 },
                 'postcss-functions': {
                     functions: functionsPostCss
                 },
                 'postcss-rtlcss': {
                     processKeyFrames: true
                 },
             },
             preset: {
                 features: {
                     'logical-properties-and-values': false,
                 },
             },
         },
```

In general, everything works correctly, however, the sass-like mixin set by the first line breaks the build.

```
.draw-info {
   $fixbug: &; /* this code is workaround, without line build breaks */

   @mixin theme primary, -20;
   position: relative;
   padding: em($gutter);
   border-radius: $border_radius;
   text-align: center;

   &::before,
   &::after {

     position: absolute;
     top: em($gutter);
     bottom: em($gutter);
     width: em(3);

     content: "";
     background-color: getColor(accent);
   }
}

```

It seems that rtlcss accepts source code as input rather than accepting it sequentially.
This is also evidenced by the ability to repeat the same bug in the playground - https://elchininet.github.io/postcss-rtlcss/#644157320bad7

the error is located here `rtlcss/utilities/rules.ts` on function `ruleHasChildren`

**Comment by elchininet** [comment]
Hi @Vilz,
I‘ll take a look at it when I got some time.
Regards

**Comment by elchininet** [comment]
Hi @Vilz,
It was easy to fix, I‘ll release a patch in some minutes.
Regards

**Comment by elchininet** [comment]
Hi @Vilz,
You can try the [version 4.0.5](https://www.npmjs.com/package/postcss-rtlcss/v/4.0.5) of the package.
Regards

**Comment by Vilz** [comment]
oh, wow! thank you!
