### ISSUE TITLE
5.1.1 release fails to install

### ISSUE THREAD

**Issue by mshima** [elchininet/postcss-rtlcss#315]
Failure log:
```
npm ERR! code 254
npm ERR! path /home/runner/work/generator-jhipster/generator-jhipster/app/node_modules/postcss-rtlcss
npm ERR! command failed
npm ERR! command sh -c npx -y only-allow pnpm
npm ERR! npm ERR! code ENOENT
npm ERR! npm ERR! syscall lstat
npm ERR! npm ERR! path /home/runner/work/generator-jhipster/generator-jhipster/app/target/lib
npm ERR! npm ERR! errno -2
npm ERR! npm ERR! enoent ENOENT: no such file or directory, lstat '/home/runner/work/generator-jhipster/generator-jhipster/app/target/lib'
npm ERR! npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! npm ERR! enoent 

```

Looks related to added preinstall script:
https://github.com/elchininet/postcss-rtlcss/blob/231ca43aa49f49e74f6592480a1506dc9f554df4/package.json#L55

https://github.com/jhipster/generator-jhipster/pull/25836
https://github.com/jhipster/generator-jhipster/pull/25825

**Comment by elchininet** [comment]
Hi @mshima,
Do you know what process tries to execute the `postinstall` script from `postcss-rtlcss` preprending `sh -c`?
Regards

**Comment by elchininet** [comment]
It doesn't matter what is trying to execute the script, it was created only to avoid confussion with multiple package managers but i am using `pnpm` for all my packages so this is not needed anymore. I'll release a patch with the removal.

**Comment by mshima** [comment]
I've tried to reproduce manually and failed, not sure why it's executed in the specific use case.
Thanks for the quick reply and fix.

**Comment by elchininet** [comment]
>I've tried to reproduce manually and failed, not sure why it's executed in the specific use case.

Do not waste time trying to reproduce it, it doesn't worth the effort 🙂

Version [5.1.2](https://www.npmjs.com/package/postcss-rtlcss/v/5.1.2) has been released with the patch.

Regards
