### ISSUE TITLE
Example of how to setup postcss-rtlcss with react-scripts (and possibly craco)

### ISSUE THREAD

**Issue by andoks** [elchininet/postcss-rtlcss#317]
I attempted and failed to setup postcss-rtlcss for processing bootstrap SCSS files and various custom .module.scss files in a create-react-app project where craco already is being used (and for completeness sake, we use react-bootstrap). I would love to have an example or recipe for enabling use of postcss-rtlcss that integrates well with the above, perhaps as a complement to the [note about using postcss-rtlcss in bootstrap](https://deploy-preview-39863--twbs-bootstrap.netlify.app/docs/5.3/getting-started/rtl/#ltr-and-rtl-at-the-same-time)

https://github.com/react-bootstrap/react-bootstrap/issues/6794

**Comment by andoks** [comment]
Found that I only needed to configure my .cracorc.js like the following [source](https://github.com/dilanx/craco/issues/402#issue-1163688378) and ensuring I took the various [scss gotchas into account](https://rtlcss.com/learn/usage-guide/value-directives/#Tip)
```
const postCssRtl = require("postcss-rtlcss");

module.exports = {
    style: {
        postcss: {
            loaderOptions: {
                postcssOptions: { 
                    plugins: [postCssRtl()],
                },
            },
        },
    },
};

```

App.module.scss
```
.test {
    background-color: aqua !important #{"/*!rtl:pink*/;"};
    padding-left: 10px !important;
}

```

**Comment by andoks** [comment]
@elchininet: yes, thank you. It might be beneficial to add an example of how to configure postcss-rtlcss with craco to your docs, in which case, feel free to copy the code from above, although I specifically do not need it anymore :smile:

**Comment by elchininet** [comment]
Hi @andoks,
I have not worked with craco before, if you make a minimum reproducible repo with your implmentation, I would be happy to include it the docs.
Regards
