### ISSUE TITLE
Plugin clobbers view transition rules

### ISSUE THREAD

**Issue by felamaslen** [elchininet/postcss-rtlcss#331]
When using the [view transition API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API), we define rules like so

```css
::view-transition-new(root) {
  animation: my-animation;
}
```

This rule has to be applied under `html`. Using RTL plugin overwrites this rule (inserting `dir:rtl` and `dir:ltr`), meaning the rule no longer applies to `html`.

One workaround is to do this:

```css
html::view-transition-new(root) { /* blah */ }
```

Another workaround is to simply ignore the plugin:

```css
/* rtl:ignore */
::view-transition-new(root) { /* blah */ }
```

However, ideally the plugins should handle this case automatically.

## Steps to reproduce

With the following input:

```css
::view-transition-new(root) {
  /* blah */
}
```

**Expected output:**

```css
[dir]::view-transition-new(root) {
  /* blah */
}
```

or potentially

```css
::view-transition-new(root) {
  &:where([dir=ltr], [dir=ltr] *) { /* blah */ }
  &:where([dir=rtl], [dir=rtl] *) { /* blah */ }
}
```

**Actual output:**

```css
[dir] ::view-transition-new(root) {
  /* blah */
}
```

[Playground link](https://elchininet.github.io/postcss-rtlcss/#66422636cfa76)

**Comment by elchininet** [comment]
Hi @felamaslen,

I'll take a look at it, the fix will be like the first example that you posted, the plugin doesn't use the `where` pseudo-class to apply the prefixes.

Meanwhile you could use the [prefixSelectorTransformer](https://github.com/elchininet/postcss-rtlcss?tab=readme-ov-file#prefixselectortransformer) option to fix the issue:

https://runkit.com/embed/bms2a5g9163p

**Comment by elchininet** [comment]
Hi @felamaslen,
In [version 5.2.0 of the library](https://www.npmjs.com/package/postcss-rtlcss/v/5.2.0) there is support for `view-transition` pseudo-classes.
Regards
