### ISSUE TITLE
How to configure postcss-rtlcss in the nuxt2 project?

### ISSUE THREAD

**Issue by goldEli** [elchininet/postcss-rtlcss#399]
I have a project using nuxt2. How to configure postcss-rtlcss in the nuxt2 project? Looking forward to your reply. Thanks a lot

**Comment by goldEli** [comment]
I have a project using nuxt2. How to configure postcss-rtlcss in the nuxt2 project?

**Comment by elchininet** [comment]
Hi @goldEli,
Do you have [PostCSS already configured](https://v2.nuxt.com/docs/features/configuration/#postcss-plugins) in your project?

**Comment by elchininet** [comment]
You can also use [nuxt-rtlcss](https://github.com/aminmokhtari94/nuxt-rtlcss) which uses this plugin behind the scenes.

**Comment by goldEli** [comment]
@elchininet Thank you for your reply, I tried the following configuration but it didn't work. I also tried [nuxt-rtlcss](https://github.com/aminmokhtari94/nuxt-rtlcss), but it only supports nuxt3.

```js
  postcss: {
      plugins: {
        'postcss-rtlcss': {},
      },
    },
```

**Comment by elchininet** [comment]
Hi @goldEli,
I will try to build an example project and upload it to a repo.
I'll let you know.
Regards

**Comment by elchininet** [comment]
Hi @goldEli,
[Here you go](https://github.com/elchininet/nuxt2-postcss-rtlcss-example).
Just change the language selector and inspect the CSS of the page (specially the styles of the selector itself).
Regards

**Comment by goldEli** [comment]
@elchininet the link is 404, thank you anyway. the problem is solved, I wrote a coustom loader using [postcss-rtlcss](https://github.com/elchininet/postcss-rtlcss) in my nuxt2 project.

**Comment by elchininet** [comment]
@goldEli,
I forgot to put it public, it is already public.
Glad that you already solved 👍🏼
Regards
