### ISSUE TITLE
Cannot be used in webpack3

### ISSUE THREAD

**Issue by WeberLong** [elchininet/postcss-rtlcss#42]
I use error reporting in webback3. How can I use it in webback3?

**Comment by elchininet** [comment]
Hi @WeberLong,
Check [the Webpack configuration](https://github.com/elchininet/postcss-rtlcss#usage-in-webpack-with-postcss-loader) using [postcss-loader](https://webpack.js.org/loaders/postcss-loader/). If you receive any errors, please, create a small repository with a minimum reproducible example of the issue.
Regards.

**Comment by elchininet** [comment]
@WeberLong, closing the issue. If you face another issue, please, fill a new one.
