### ISSUE TITLE
Not working in Next.js postcss

### ISSUE THREAD

**Issue by ahmed3hamdan** [elchininet/postcss-rtlcss#53]
According to [next.js docs](https://nextjs.org/docs/advanced-features/customizing-postcss-config#customizing-plugins), `require()` is not allowed to import the PostCSS Plugins. Plugins must be provided as strings.

My `postcss.config.js`
```javascript
module.exports = {
    plugins: ["postcss-rtlcss"]
}
```

Error when running next.js development server
```
Error: [Object Object] is not a PostCSS plugin
```

What is the proper way to use `postcss-rtlcss`  in next.js?

**Comment by elchininet** [comment]
@ahmed3hamdan, I'll try to search a solution. If not, I can release a major version exporting the plugin as the default module to support Next.js. I'll keep you updated about this.

**Comment by elchininet** [comment]
@ahmed3hamdan, please, try the version [3.0.0](https://www.npmjs.com/package/postcss-rtlcss/v/3.0.0). I've exported the plugin as default instead of a named export.

**Comment by ahmed3hamdan** [comment]
Works after updating to version 3.0.0 and updating postcss to version 8
