### ISSUE TITLE
Latest version cannot be used with postcss@7

### ISSUE THREAD

**Issue by Leruiz** [elchininet/postcss-rtlcss#69]
We use postcs@7 and then install the latest version.  it has errors when build by webpack

**Comment by elchininet** [comment]
Hi @Leruiz, latest version is to use only with postcss@8+, if you want to use postcss@7, you need to use the legacy version (last one is 1.6.5). Latest features are not included in the legacy version, but if you need some new feature I can implement it there also:

![image](https://user-images.githubusercontent.com/3728220/113150826-c40be280-9234-11eb-9c52-35d6dae90675.png)

**Comment by elchininet** [comment]
Hi @Leruiz,
The latest features have been included in the legacy version, the last legacy version at the moment is v1.6.7.
I also added information about the legacy version in the README to show how to install it and how to use it.
Closing this issue.
