### ISSUE TITLE
Is the license GPL 3 or MIT?

### ISSUE THREAD

**Issue by bschlenk** [elchininet/postcss-rtlcss#74]
Hi! I'm looking into using this plugin in place of the unmaintained [postcss-rtl](https://github.com/vkalinichev/postcss-rtl). I'm curious what the license is supposed to be... the [license field in package.json](https://github.com/elchininet/postcss-rtlcss/blob/master/package.json#L40) says MIT, but the [LICENSE.md file](https://github.com/elchininet/postcss-rtlcss/blob/master/LICENSE.md) says GPL.

Thanks!

**Comment by elchininet** [comment]
Hi @bschlenk the license is definitely [GNU GPL V3](https://github.com/elchininet/postcss-rtlcss/blob/master/LICENSE.md). The version in package.json was a mistake and [it is already fixed](https://github.com/elchininet/postcss-rtlcss/commit/2a6ba2ead640e9b54bd95e9e84618c203a5d1101).

**Comment by bschlenk** [comment]
That’s great, thank you!
