### ISSUE TITLE
Problem with bootstrap variable customization

### ISSUE THREAD

**Issue by ak-14** [elchininet/postcss-rtlcss#76]
Hello,
Thank you for developing and maintaining this plugin. I am trying to use this plugin with bootstrap 5 and having a problem. I am modifying the $font-family-sans-serif variable to include an Arabic font as shown in their documentation. In my scss I have the following:

```
$font-family-sans-serif:
  system-ui,
  ...
  #{"/*rtl:prepend:Tajawal,*/"} !default;

@import '~bootstrap/scss/bootstrap';
```

The output css will have the following:

```
[dir="ltr"] :root {
  --bs-font-sans-serif: system-ui, ...; }

[dir="rtl"] :root {
  --bs-font-sans-serif: Tajawal,system-ui, ...; }
```

but it does not work as expected. Previously I used postcss-rtl and the same css worked so I tried to see what the difference is and I found that the output is the same except it does not contain a space between the brackets and :root like this: ```[dir="ltr"]:root``` which works as expected. Do you think there is a bug here or is it supposed to be like this?

**Comment by elchininet** [comment]
Hi @ak-14, could you create a small reproducible example with the issue to understand what is happening?
With your code snippets, it is hard to reproduce it without the correct settings and configurations.

**Comment by elchininet** [comment]
Hi @ak-14,
The bug has been fixed. You can use the version `3.3.2` or the `1.6.9` if you are using the legacy version.
Regards!

**Comment by ak-14** [comment]
Amazing @elchininet! I really appreciate fixing this in such a short time! I can confirm that it is working now!
