### ISSUE TITLE
Output with one direction only

### ISSUE THREAD

**Issue by FaridAghili** [elchininet/postcss-rtlcss#78]
Is it possible to get output for one direction only? Let's say give it a LTR source and get RTL output only.

**Comment by elchininet** [comment]
Hi, @FaridAghili,

That is what [RTLCSS](https://github.com/MohammadYounes/rtlcss) does. Poscss-RTLSS is based on this plugin to generate LTR and RTL rules in a single file, but if you want to convert an entire input to RTL you should use RTLCSS.

Regards!

**Comment by FaridAghili** [comment]
Can I use RTLCSS as postcss plugin?
Sorry, I know it's another topic.
________________________________

**Comment by elchininet** [comment]
Yes, [it can be used as a Postcss plugin](https://rtlcss.com/learn/usage-guide/install/#Advanced-usage) and it is very customizable.

**Comment by FaridAghili** [comment]
Thank you.
