### ISSUE TITLE
how to transform inline css ?

### ISSUE THREAD

**Issue by linliya** [elchininet/postcss-rtlcss#85]
eg.` <div style="{{marginRight: 10}}">test</div>`

**Comment by elchininet** [comment]
Hi @linliya,

This library is a [postcss](https://postcss.org/) plugin. So it takes as input a string file and returns another string. It is not intended for cases like yours.

In your case, it seems that you are working with JSX and React, in that case, I would recommend using some kind of CSS in JS like [@emotion](https://emotion.sh/docs/introduction) and some [stylis plugin](https://github.com/emotion-js/emotion/issues/793#issuecomment-413486164) to create the RTL styles for you automatically.

Closing this issue.

Regards
